module red_pitaya_ps (
  inout  logic [54-1:0] FIXED_IO_mio     ,
  inout  logic          FIXED_IO_ps_clk  ,
  inout  logic          FIXED_IO_ps_porb ,
  inout  logic          FIXED_IO_ps_srstb,
  inout  logic          FIXED_IO_ddr_vrn ,
  inout  logic          FIXED_IO_ddr_vrp ,
  inout  logic [15-1:0] DDR_addr   ,
  inout  logic [ 3-1:0] DDR_ba     ,
  inout  logic          DDR_cas_n  ,
  inout  logic          DDR_ck_n   ,
  inout  logic          DDR_ck_p   ,
  inout  logic          DDR_cke    ,
  inout  logic          DDR_cs_n   ,
  inout  logic [ 4-1:0] DDR_dm     ,
  inout  logic [32-1:0] DDR_dq     ,
  inout  logic [ 4-1:0] DDR_dqs_n  ,
  inout  logic [ 4-1:0] DDR_dqs_p  ,
  inout  logic          DDR_odt    ,
  inout  logic          DDR_ras_n  ,
  inout  logic          DDR_reset_n,
  inout  logic          DDR_we_n   ,
  output logic  [4-1:0] fclk_clk_o ,
  output logic  [4-1:0] fclk_rstn_o,
  gpio_if.m              gpio,
  input logic            irq,
  axi4_lite_if.m         bus
);

logic [4-1:0] fclk_clk ;
logic [4-1:0] fclk_rstn;

assign fclk_rstn_o = fclk_rstn;

BUFG fclk_buf [4-1:0] (.O(fclk_clk_o), .I(fclk_clk));

system system (
  .FIXED_IO_mio      (FIXED_IO_mio     ),
  .FIXED_IO_ps_clk   (FIXED_IO_ps_clk  ),
  .FIXED_IO_ps_porb  (FIXED_IO_ps_porb ),
  .FIXED_IO_ps_srstb (FIXED_IO_ps_srstb),
  .FIXED_IO_ddr_vrn  (FIXED_IO_ddr_vrn ),
  .FIXED_IO_ddr_vrp  (FIXED_IO_ddr_vrp ),
  .DDR_addr          (DDR_addr   ),
  .DDR_ba            (DDR_ba     ),
  .DDR_cas_n         (DDR_cas_n  ),
  .DDR_ck_n          (DDR_ck_n   ),
  .DDR_ck_p          (DDR_ck_p   ),
  .DDR_cke           (DDR_cke    ),
  .DDR_cs_n          (DDR_cs_n   ),
  .DDR_dm            (DDR_dm     ),
  .DDR_dq            (DDR_dq     ),
  .DDR_dqs_n         (DDR_dqs_n  ),
  .DDR_dqs_p         (DDR_dqs_p  ),
  .DDR_odt           (DDR_odt    ),
  .DDR_ras_n         (DDR_ras_n  ),
  .DDR_reset_n       (DDR_reset_n),
  .DDR_we_n          (DDR_we_n   ),
  .FCLK_CLK0         (fclk_clk[0]),
  .FCLK_CLK1         (fclk_clk[1]),
  .FCLK_CLK2         (fclk_clk[2]),
  .FCLK_CLK3         (fclk_clk[3]),
  .FCLK_RESET0_N     (fclk_rstn[0]),
  .FCLK_RESET1_N     (fclk_rstn[1]),
  .FCLK_RESET2_N     (fclk_rstn[2]),
  .FCLK_RESET3_N     (fclk_rstn[3]),
  .PL_ACLK            (bus.ACLK   ),
  .PL_ARESETn         (bus.ARESETn),
  .M_AXI_GP0_araddr   (bus.ARADDR ),
  .M_AXI_GP0_arprot   (bus.ARPROT ),
  .M_AXI_GP0_arready  (bus.ARREADY),
  .M_AXI_GP0_arvalid  (bus.ARVALID),
  .M_AXI_GP0_awaddr   (bus.AWADDR ),
  .M_AXI_GP0_awprot   (bus.AWPROT ),
  .M_AXI_GP0_awready  (bus.AWREADY),
  .M_AXI_GP0_awvalid  (bus.AWVALID),
  .M_AXI_GP0_bready   (bus.BREADY ),
  .M_AXI_GP0_bresp    (bus.BRESP  ),
  .M_AXI_GP0_bvalid   (bus.BVALID ),
  .M_AXI_GP0_rdata    (bus.RDATA  ),
  .M_AXI_GP0_rready   (bus.RREADY ),
  .M_AXI_GP0_rresp    (bus.RRESP  ),
  .M_AXI_GP0_rvalid   (bus.RVALID ),
  .M_AXI_GP0_wdata    (bus.WDATA  ),
  .M_AXI_GP0_wready   (bus.WREADY ),
  .M_AXI_GP0_wstrb    (bus.WSTRB  ),
  .M_AXI_GP0_wvalid   (bus.WVALID ),
  .GPIO_tri_i (gpio.i),
  .GPIO_tri_o (gpio.o),
  .GPIO_tri_t (gpio.t),
  .IRQ        (irq)
);

endmodule: red_pitaya_ps
